apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-demo
  region: ap-south-1
  version: "1.21"
vpc:
  id: "vpc-04718bbb058c1e087"
  cidr: "172.31.0.0/16"
  securityGroup: "sg-09c5e7f0d2217307a"
  subnets:
    public:
      ap-south-1c:
          id: "subnet-03a4eae2012725eaf"
          cidr: "172.31.16.0/20"
      ap-south-1a:
          id: "subnet-0df4dc2cdecd37875"
          cidr: "172.31.32.0/20"
managedNodeGroups:
  - name: eks-ng
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    instanceType: t3.xlarge
    volumeSize: 80
    privateNetworking: false
    tags:
      costid: devops
    iam:
      withAddonPolicies:
        externalDNS: true
        autoScaler: true
        ebs: true
        efs: true
        cloudWatch: true
        
