apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-config
  
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: root
  POSTGRES_PASSWORD: root123
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: pg-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pg-sc
  mountOptions:
    - tls
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-03278841e0673e0d4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: pg-sc
  resources:
    requests:
      storage: 1Gi
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: postgres
 labels:
   app: postgres
spec:
 replicas: 1
 selector:
   matchLabels:
     app: postgres
 template:
   metadata:
     labels:
       app: postgres
   spec:
     containers:
     - name: postgres
       image: postgres:10.4
       imagePullPolicy: "IfNotPresent"
       ports:
         - containerPort: 5432
       envFrom:
         - configMapRef:
             name: pg-config
       volumeMounts:
         - mountPath: /var/lib/postgresql/data
           name: postgredb
     volumes:
       - name: postgredb
         persistentVolumeClaim:
           claimName: pg-claim        
